### ISSUE TITLE
handler callback does not receive argument

### ISSUE THREAD

**Issue by sungwoncho** [rvagg/github-webhook-handler#11]
There is an inaccurate information in the README.

As per the [code](https://github.com/rvagg/github-webhook-handler/blob/master/github-webhook-handler.js#L31), when the `req.url` does not match the `path` option of the handler, callback is executed without any arguments passed.

i.e.

``` javascript
...
    if (req.url.split('?').shift() !== options.path)
      return callback()
...
```

However, the README says we can pass `err` to the callback.

``` javascript
  handler(req, res, function (err) {
    res.statusCode = 404
    res.end('no such location')
  })
```

But `err` in this case is always undefined.

**Comment by rvagg** [comment]
there are various conditions in which you'll get the callback with an error: https://github.com/rvagg/github-webhook-handler/blob/master/github-webhook-handler.js#L40

I'm wondering however if that even makes sense, it emits an error and that should suffice, perhaps we should remove the callback-if-error case completely.

**Comment by rjz** [comment]
> it emits an error and that should suffice, perhaps we should remove the callback-if-error case completely.

@sungwoncho, would this be acceptable to you? Simplifying the interface will promote consistency on any future changes, as well as cutting down a bit of code and the README.

It looks like fixing #8 will solve the original issue in any case, but this seems like as good an excuse as any to `deprecate` the callback interface.

**Comment by sungwoncho** [comment]
@rjz it's been a while since I filed this issue and it's hard to jog the memory back.

I think that solution is acceptable. But it's kind of confusing as a user that sometimes I get a callback with an error and sometimes I have to listen to the error event.
