### ISSUE TITLE
Express and signature error

### ISSUE THREAD

**Issue by root-io** [rvagg/github-webhook-handler#14]
Edit: Nevermind, I use `github-webhook-middleware` for Express :)

I have the error below, I checked multiple times, the secret seems to be correct. Maybe it's because the req sent by Express is different from the one sent with http.createServer ?

`Error: X-Hub-Signature does not match blob signature`

route

    app.post('/webhook', webhook);

controller

    var createHandler = require('github-webhook-handler');
    var handler = createHandler({ path: '/webhook', secret: "mysecret" });

    module.exports = function(req, res) {
      handler(req, res, function (err) {
        res.statusCode = 404;
        res.end('no such location');
      });

      handler.on('error', function (err) {
        console.error('Error:', err.message);
      });

       handler.on('push', function(event) {
         var comps = event.payload.ref.split('/');
         if (comps[2] != 'production') {
           console.log('Received a push on %s and no build has is triggered', comps[2]);
           return;
         }
         console.log('Received a push on production, build started...');
         exec('./scripts/deploy', function(error, stdout, stderr) {
           console.log(stdout);
           if (error != null) {
             console.log('Error during the execution of redeploy: ' + stderr);
           }
         });
       });
    };

**Comment by laem** [comment]
The solution is [here](http://stackoverflow.com/a/30421855)

**Comment by levithomason** [comment]
If others run into this, you might be using `body-parser` before `github-webhook-handler`.  Putting the body parser middleware after the webhook middleware solved this for me.

**Comment by gsaslis** [comment]
Having the same issue here. 

@laem tbh, i didn't understand how you solved this. 

@levithomason I know it's a looong time, but when you say "putting it before", what do you mean?
