### ISSUE TITLE
Multiple handlers

### ISSUE THREAD

**Issue by isvaljek** [rvagg/github-webhook-handler#21]
Is having a multiple webhook handlers in a single node script a supported code path?
Like:
http://example.com/pushmepullme/23
http://example.com/pushmepullme/36
http://example.com/pushmepullme/37

I tried creating an array of handlers but it seems to only work with element 0.

**Comment by rjz** [comment]
It should be possible to create multiple handlers and chain them through their error handlers, but I wonder if the use-case could be addressed (given knowledge of the inbound events) by a single handler.

```js
handler.on('issues', function (event) {
  switch(event.payload.repository.id) {
    case 23: return doThis();
    case 36: return doThat();
    case 37: return doSomethingElseEntirely();
  }
});
```

Would something like this work for what you have in mind?

**Comment by isvaljek** [comment]
In my case even the url must be different because (correct me if I'm wrong) I can't send custom data from github and I can have multiple "deployment scenarios/users" per single repository. I need to somehow pass in the deployment_id.
That is the number at the end of my sample url: http://example.com/pushmepullme/23 <- deploy_id

**Comment by rjz** [comment]
Got it––thanks, @isvaljek. Is there any way to configure the deployment scenarios/users within the app (rather than within github), though?

(please forgive all the questions! Just trying to imagine any alternative approaches that could address the specific need before we contemplate a code change to address it.)

**Comment by isvaljek** [comment]
I grab the deployment details from a different app by deploy_id. It's just an xhr call to the other app, so I guess it could all be stored locally. What I meant to say is that I don't know of a way to pass any extra data from github webhook to my app.
So, having to create a webhook url beforehand, I'm cornered into hardcoding the deployment_id into both github webhook and my app. 
My app only has knowledge of deploy_ids so I thought I could create an array of handlers with your package that are 1:1 with github webhook urls.

**Comment by rjz** [comment]
There's been additional discussion of a similar case in #22 that I believe could address this need. Closing this out to move further discussion over there, but please correct me if my understanding's off-base!
