### ISSUE TITLE
data errs on parse

### ISSUE THREAD

**Issue by mmclau14** [rvagg/github-webhook-handler#26]
```data.toString()```
errs on parse.
```
//console.log(data.toString());
//console.log(decodeURIComponent(data.toString()));
      try {
        obj = JSON.parse(decodeURIComponent(data.toString()))
      } catch (e) {
        return hasError(e)
      }
```
was able to get a bit closer. but the payload query key is still in the string

had to update to the following line to get it to work
```
        obj = JSON.parse(decodeURIComponent(data.toString()).slice(8))
```
am I supposed to be using some sort of middleware?

I am pulling from a private repo. Not sure if github's api is different for that

**Comment by rjz** [comment]
@mmclau14, could you provide an example of `data` leading up to this issue?

**Comment by rjz** [comment]
Also, could you double-check that your webhook is [configured to send json directly](https://developer.github.com/webhooks/creating/#content-type)?

**Comment by mattpardee** [comment]
I believe I'm seeing this as well, on the `push` event. Will dig deeper to confirm.

**Comment by mattpardee** [comment]
Major facepalm. Of course there was a problem because I was posting as a form, not as JSON from the github webhook config.

**Comment by mmclau14** [comment]
thanks for looking into this guys. completely missed these emails. glad you were able to find it. is there any more info i can help with?

**Comment by rjz** [comment]
Cheers, @mmclau14! Before we close this up: did the config change fix your issue as well?

**Comment by mmclau14** [comment]
so i don't believe there was a configuration difference on my end. and i do not think i am using the modified version because i used a script to deploy to app engine that does an install. i actually found this package because it was a dependency of another package, nuts-serve or whatever autoupdating package i'm using. because it's working on my end and it seems like you guys were able to replicate i will say yes, we're good. thanks!

**Comment by rjz** [comment]
Beauty. Closing out for now, but let's revisit if anything else comes up. Thanks again, all!
