### ISSUE TITLE
why buffer-equal-constant-time instead of Buffer.equals ?

### ISSUE THREAD

**Issue by kapouer** [rvagg/github-webhook-handler#27]
I feel stupid to not understand what's happening here.

**Comment by rjz** [comment]
No worries! The constant-time comparison dates back to https://github.com/rvagg/github-webhook-handler/commit/e7f93bbcbb4699a0811debd00e4de6483d787a97. It's there to address an (admittedly rather improbable) [timing attack](https://en.wikipedia.org/wiki/Timing_attack) against the signature.

**Comment by kapouer** [comment]
Fantastic but how the hell is it supposed to address that attack ? in which way ?

**Comment by rjz** [comment]
Imagine an efficient equality check between (e.g.) `'abcdef'` and `'zzzzzz'`, which would return false at the first character. If we repeat, replacing `'z'` with other characters, we'll note that `'azzzzz'` takes twice as long to return. Using constant-time comparison ensures that we'll take the same time (a function of buffer size) to reject non-matching buffers regardless of when we learn enough to fail them.

In the real world this obviously gets trickier. CPU scheduling, GC runs, blocking calls in the event loop, and their ilk will all complicate timing--and that's if we're on a single machine/core/process. Factor in network latency, and a finicky attack becomes pretty unlikely. But a little paranoia shouldn't hurt!

**Comment by jdanyow** [comment]
>Using a plain == operator is not advised. A method like secure_compare performs a "constant time" string comparison, which renders it safe from certain timing attacks against regular equality operators.
-- https://developer.github.com/webhooks/securing/#validating-payloads-from-github
