### ISSUE TITLE
Hmac Failure in GCP Functions

### ISSUE THREAD

**Issue by stephengroat** [rvagg/github-webhook-handler#35]
Trying the following code in GCP Functions, getting a bunch of `X-Hub-Signature` errors. Any advice?

```javascript
var createHandler = require('github-webhook-handler');

exports.createServer = function createServer(req, res) {
  console.log(req.headers['x-hub-signature']);
  console.log('sha1=', crypto.createHmac('sha1', 'test').update(JSON.stringify(req.body)).digest('hex'));
  handler(req, res, function (err) {
    console.error('Error:', err)
    res.statusCode = 404
    res.end('no such location')
  });
};

var createApp = require('github-app');

var app = createApp({
  id: process.env.APP_ID,
  cert: '123'
});

handler.on('error', function (err) {
  console.error('Error:', err.message)
});
```

Logs:
```
sha1=2fb7be3e70d5fd70a02b24fd8076113322224bb7
sha1=2fb7be3e70d5fd70a02b24fd8076113322224bb7
Error: X-Hub-Signature does not match blob signature
```

**Comment by Philmod** [comment]
I am having the same issue, did you find what is the problem or even a solution?

**Comment by rtm** [comment]
By the time this package gets its hands on the payload, it has already been pre-processed by the GCP infrastructure, into the equivalent of having been run through express with bodyparser. You could try `express-github-webhook`.

**Comment by rvagg** [comment]
sorry closing this because I don't have an answer, it's not in my scope of use but I'd be happy to receive pull requests that might address this
