### ISSUE TITLE
Multiple creations will cause an exception to occur

### ISSUE THREAD

**Issue by brizer** [rvagg/github-webhook-handler#40]
Multiple creations will cause an exception to occur.
I have an example, if I  cancel the comment, an exception will occur when the hooks occur.
[example](https://github.com/brizer/hooks_for_serve_data/blob/master/index.js#L5)

``` js
var handler = createHandler({ path: "/pushCode", secret: "study" }); 
// var handlerInterview = createHandler({ path: "/pushCodeInterview", secret: "study" }); 
http
    .createServer(function (req, res) {
        console.log(req.path)
        handler(req, res, function (err) {
            res.statusCode = 404;
            res.end("no such location");
        });
        // handlerInterview(req, res, function (err) {
        //     res.statusCode = 404;
        //     res.end("no such location");
        // });
    })
    .listen(7777);
```

Because when I request this hooks `/pushCodeInterview`, the first handler will return callback, but not go on.

**Comment by rvagg** [comment]
There's a link on the README to [this](https://github.com/rvagg/github-webhook-handler/pull/22#issuecomment-274301907) that I think might solve your issue.

It could be something we could accommodate natively but it would take some work I think. I haven't had my head in this code for a while so can't say for sure but if you're keen to try and make it work you're welcome to open a pull request, one that doesn't break backward compatibility would be particularly appreciated.
