### ISSUE TITLE
{"error":"No X-Hub-Signature found on request"}

### ISSUE THREAD

**Issue by Gan-Jason** [rvagg/github-webhook-handler#43]
I've  been disturbed about this error for a while，until  i resolved it by configuring the webhook secret. The secret parameter must be set since it need a x-hub-signature,does the secret necessary and what about cancel this expression:if (!sig).

**Comment by rvagg** [comment]
Sorry @Gan-Jason I can't quite figure out what you're reporting here. The signature is a necessary part of the process, are you suggesting it shouldn't be for some reason or is this a usability or documentation problem?

**Comment by Gan-Jason** [comment]
i didn't konw the signature is necessary ,forget what i said and thank u
