### ISSUE TITLE
Filtering of params in QSA

### ISSUE THREAD

**Issue by kennydee** [rvagg/github-webhook-handler#8]
Hi,
First, Thanks for your work.
I got a question, for a small project, i use `github-webhook-handler` to handle all of my "webhook"

It's a server receiving QSA to know which webhook must be launched `/webhook?nameOfTheWebhook` 
To made it work, I have to hack your lib to get rid of the two line filtering `?` 

``` javascript
if (req.url.split('?').shift() !== options.path)
      return callback()
```

Why do you forbid QSA usage ?
Is there any way to accept them (or to deal with dynamic routing `/routing/[a-z]+`) without hacking your library ?

Thanks again :)
Kenny

**Comment by rvagg** [comment]
I just think this isn't a use-case that's been dealt with yet, I'd be happy to see a pull request to make it work, just be sure to include tests to verify that it works properly

**Comment by kennydee** [comment]
Hmm i have no problem in making a pull request, but this one will only delete code :)
the two line quoted in my initial post, and the according test for rejecting path with query string.

If there is no reason to forbid QSA, and you confirm i can delete those two things, i will make a pull request for sure :)
if there is a reason, i'll be happy to talk about it.
thanks

**Comment by kennydee** [comment]
hi, any news on that ? Thanks you

**Comment by rjz** [comment]
@kennydee, I think this would be a fair change. Query strings are still valid within a `POST` are still valid HTTP, and I think it's reasonable to trust downstream code to filter/validate them as needed.

If you're still up to submit that pull-request (and no-one else expresses concerns) I'd be happy to bring it in!

**Comment by rvagg** [comment]
removing the `?` split for a semver-major release
